const books = [
  {
    title: "The Great Gatsby",
    genre: "Fiction",
    publication_year: 1925,
    author: "F. Scott Fitzgerald",
    publisher: "Scribner",
  },
  {
    title: "To Kill a Mockingbird",
    genre: "Fiction",
    publication_year: 1960,
    author: "Harper Lee",
    publisher: "J. B. Lippincott & Co.",
  },
  {
    title: "1984",
    genre: "Science Fiction",
    publication_year: 1949,
    author: "George Orwell",
    publisher: "Secker & Warburg",
  },
  {
    title: "Pride and Prejudice",
    genre: "Romance",
    publication_year: 1813,
    author: "Jane Austen",
    publisher: "T. Egerton, Whitehall",
  },
  {
    title: "The Catcher in the Rye",
    genre: "Fiction",
    publication_year: 1951,
    author: "J. D. Salinger",
    publisher: "Little, Brown and Company",
  },
  {
    title: "Harry Potter and the Philosopher's Stone",
    genre: "Fantasy",
    publication_year: 1997,
    author: "J. K. Rowling",
    publisher: "Bloomsbury",
  },
  {
    title: "The Da Vinci Code",
    genre: "Mystery",
    publication_year: 2003,
    author: "Dan Brown",
    publisher: "Doubleday",
  },
